
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(forecast)
library(TTR)
library(Metrics)
library(tidyr)
library(dplyr)
library(zoo)
library(hydroGOF)
```



```{r}

train <- read.csv('train.csv')
test <- read.csv('test.csv')

glimpse(train)


```

```{r}

train_items <- unique(train$Item_ID)
test_items <- unique(test$Item_ID)

```

```{r}

NRMSE_tbats_p <- NULL
NRMSE_tbats_s <- NULL

```


### TBATS

```{r}


for (i in 1:length(train_items))
{
  
  temp <- train[train$Item_ID==train_items[i],]

  temp.ts.p <- ts(temp[,7],frequency =365, start=c(2014,1,1))
  temp.ts.s <- ts(temp[,8],frequency =365, start=c(2014,1,1))

  #TBATS for price and sales
  tbats_p <- tbats(temp.ts.p,use.box.cox=TRUE,use.trend=TRUE,use.damped.trend=FALSE,use.parallel=TRUE, num.cores=3)
  tbats_s <- tbats(temp.ts.s,use.box.cox=TRUE,use.trend=TRUE,use.damped.trend=FALSE,use.parallel=TRUE, num.cores=3)
  
  NRMSE_tbats_p[i] <- nrmse(tbats_p$fitted.values,temp.ts.p)
  NRMSE_tbats_s[i] <- nrmse(tbats_s$fitted.values,temp.ts.s)
  
  
  temp <- test[test$Item_ID==train_items[i],]
  
  if (nrow(temp)>0)
  {
    pred_price <- forecast(tbats_p,184)$mean
    pred_sales <- forecast(tbats_s,184)$mean
    test_op <- data.frame(ID=temp[,6],Number_Of_Sales=pred_sales,Price=pred_price)
    write.table(test_op, "testop1.csv", sep = ",", append = T,col.names = F)
  }
  
  if (i%%5==0)
  {
    print(i)
  }

}

```


```{r}
mp <- mean(NRMSE_hw_p);mp
ms <- mean(NRMSE_hw_s);ms

```

```{r}

np <- sum(NRMSE_hw_p)/(sum(NRMSE_hw_p)+sum(NRMSE_hw_s));np
ns <- sum(NRMSE_hw_s)/(sum(NRMSE_hw_p)+sum(NRMSE_hw_s));ns

```


```{r}

(np*mp)+(ns*ms)

```



