
```{r}
library(dplyr)
library(forecast)
library(TTR)
library(Metrics)
library(tidyr)
library(dplyr)
library(zoo)
library(hydroGOF)

```


```{r}
train <- read.csv('train.csv')
test <- read.csv('test.csv')

```

```{r}
summary(train)
summary(test)

```

```{r}
train1 <- separate(train,Datetime,c("year","month","day"),sep='-')

```

```{r}
train1$year <- as.factor(train1$year)
train1$month <- as.factor(train1$month)
train1$day <- as.factor(train1$day)
train1$Category_3 <- as.factor(train1$Category_3)
train1$Category_2 <- as.factor(train1$Category_2)

summary(train1)

```


```{r}
test1 <- separate(test,Datetime,c("year","month","day"),sep='-')

```

```{r}
test1$year <- as.factor(test1$year)
test1$month <- as.factor(test1$month)
test1$day <- as.factor(test1$day)
test1$Category_3 <- as.factor(test1$Category_3)
test1$Category_2 <- as.factor(test1$Category_2)

summary(test1)

```

```{r}

train1_test1 <- rbind(train1[,c(2:8)],test1[,c(1:4,7,6,5)])

names(train1_test1)
nrow(train1_test1)

```


```{r}
library(missForest)
library(doParallel)
registerDoParallel(cores = 4)

train1_test1.imp <- missForest(train1_test1,parallelize = "variables")

train1_test1.imp$OOBerror

```

```{r}

train2 <- train1_test1.imp$ximp[1:nrow(train1),]
test2 <-  train1_test1.imp$ximp[-c(1:nrow(train1)),]


```

```{r}

train2_sales <- train2 %>% mutate(Number_Of_Sales=train1$Number_Of_Sales,Price=train1$Price)
train2_price <- train2 %>% mutate(Price=train1$Price)
test2 <- test2 %>% mutate(ID=test1$ID)

```

```{r}
names(train2_price)
names(train2_sales)
names(test2)

```


```{r}

write.csv(train2_price,'train2_price.csv')
write.csv(train2_sales,'train2_sales.csv')
write.csv(test2,'test2.csv')

```

```{r}
train_items <- unique(train2_price$Item_ID)
test_items <- unique(test2$Item_ID)
```


### Defining parameters

```{r}

library(caret)

#Define the training control

fitcontrol <- trainControl(method="cv",number=1,savePredictions='final')

```




```{r}

#set.seed(101)
library(xgboost)

predictorsp <- c("year","month","day","Category_3","Category_2","Category_1")
predictorss <- c("year","month","day","Category_3","Category_2","Category_1","Price")

outcomep <- "Price"
outcomes <- "Number_Of_Sales"



```


### xgboost

```{r}
for (i in 1:length(train_items))
{
  
  temp_train <- train2_price[train2_price$Item_ID==train_items[i],]
  temp_test <- test2[test2$Item_ID==train_items[i],]
  
  if (nrow(temp_test)>0)
  {
    cl <- makeCluster(4); registerDoParallel(4)
    
    model_xgbp <- train(Price ~ year+month+day+Category_3+Category_2+Category_1,
                  data=temp_train,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
    stopCluster(cl);
    
    
    predict_model_xgbp <- predict(model_xgbp,temp_test[,predictorsp])
    
    temp_train <- train2_sales[train2_sales$Item_ID==train_items[i],]
    temp_test <- temp_test %>% mutate(Price=predict_model_xgbp)
    
    cl <- makeCluster(4); registerDoParallel(4)
    
    model_xgbs <- train(Number_Of_Sales ~ year+month+day+Category_3+Category_2+Category_1+Price,
                  data=temp_train,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
    
    stopCluster(cl);
    
    predict_model_xgbs <- predict(model_xgbs,temp_test[,predictorss])
    
    test_op <- data.frame(ID=temp_test[,8],Number_Of_Sales=predict_model_xgbs,Price=predict_model_xgbp)
    write.table(test_op, "testop2.csv", sep = ",", append = T,col.names = F)
  }
  
  if (i%%10==0)
  {
    print(i)
  }

}
```


