---
title: "JetRail"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

https://github.com/sauravkaushik8/Fractal-Analytics-Hackathon/blob/master/Fractal%20Hack%20Script.R


```{r}
library(tidyr)
library(dplyr)
library(forecast)
library(TTR)
library(Metrics)
library(dplyr)
library(zoo)
library(ggplot2)
library(readr)
library(xts)
library(smooth)
library(caret)

```


```{r}
train <- read_csv('Train_SU63ISt.csv')

```

```{r}
test <- read_csv("Test_0qrQsBZ.csv")
```

```{r}

time_index <- seq(from = as.POSIXct("2012-08-25 00:00"), to = as.POSIXct("2014-09-25 23:00"), by = "hour")

train_hr <- xts(train$Count, order.by = time_index)

head(train_hr);tail(train_hr);

```

```{r}
plot(train_hr)
```

```{r}

x <- msts(train$Count, seasonal.periods=c(24,24*7,365.25*24), start=2012+34/52)
plot(x)

```

#decomposition
```{r}

stl1 <- stl(x,s.window = "periodic")
plot(stl1)

```

### Simple moving average

```{r}

#SMA
SMA_test <- sma(x, h=nrow(test),silent="graph")

test_op <- data.frame(ID=test$ID,Count=SMA_test$forecast)

colnames(test_op) <- c("ID","Count")
```

```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
#dir <- "D:\\Users\\bharadwaj\\Desktop\\DS\\Datasets\\AV"
write_csv(test_op, file.path(dir, "sma.csv"), col_names = TRUE)


```


### Simple moving average 1

```{r}

#SMA
SMA_test1 <- sma(x, ic=c("BIC"),h=nrow(test),silent="graph", holdout = TRUE, accuracy="sMSE")

test_op <- data.frame(test$ID, SMA_test1$forecast)

colnames(test_op) <- c("ID","Count")
```

```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "sma1.csv"), col_names = TRUE)


```


### tslm - add

```{r}

#SMA
tslm_add <- tslm(x ~ trend + season)
summary(tslm_add)
#test_op <- data.frame(test$ID, SMA_test1$forecast)

#colnames(test_op) <- c("ID","Count")
```

```{r}


f1 <- forecast(tslm_add,h=nrow(test))
#f1 <- predict(tslm_add,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "tslm1.csv"), col_names = TRUE)


```



### tslm - add

```{r}

#SMA
tslm_add1 <- tslm(x ~ trend)
summary(tslm_add1)
#test_op <- data.frame(test$ID, SMA_test1$forecast)

#colnames(test_op) <- c("ID","Count")
```

```{r}


f1 <- forecast(tslm_add1,h=nrow(test))
#f1 <- predict(tslm_add,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "tslm2.csv"), col_names = TRUE)


```


```{r}
#ar1 <- acf(tslm_add$residuals)
#ar1$acf[2]

#library(nlme)

#tslm_gls <- gls(x ~ time(x) ,cor=corAR1(ar1$acf[2]))
tslm_add2 <- tslm(x ~ time(x))
summary(tslm_add2)


```

```{r}


#f1 <- forecast(tslm_add2,h=nrow(test))
f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "tslm3.csv"), col_names = TRUE)


```

#arima
```{r}

arima_1 <- auto.arima(x)
summary(arima_1)

```

```{r}

arima_2 <- auto.arima(x1)
summary(arima_2)

```


```{r}
arima_3 <- auto.arima(x2)
summary(arima_3)

arima_4 <- auto.arima(x3)
summary(arima_4)


```






```{r}


f1 <- forecast(arima_2,h=nrow(test))
#f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

#dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "arima2.csv"), col_names = TRUE)


```

#tbats
```{r}

tbats_1 <- tbats(x)
summary(tbats)

```

```{r}


f1 <- forecast(arima_1,h=nrow(test))
#f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "arima1.csv"), col_names = TRUE)


```


```{r}

train1_hr <- to.hourly(train_hr)
train2_hr <- ts(as.vector(train1_hr[,4]),start=c(2012,08,25),end=c(2014,09,25),frequency = 24)
train2_hr

```


```{r}

#SMA

x2 <- ts(train$Count, frequency=24*7)
time(x2)

SMA_test4 <- sma(x2, h=nrow(test),silent="graph")

test_op <- data.frame(ID=test$ID,Count=SMA_test4$forecast)

colnames(test_op) <- c("ID","Count")
```

```{r}

#dir <- "D:\\Users\\bharadwaj\\Desktop\\DS\\Datasets\\AV"
write_csv(test_op, file.path(dir, "sma3.csv"), col_names = TRUE)


```


### Simple moving average 1

```{r}

#SMA
SMA_test1 <- sma(x, ic=c("BIC"),h=nrow(test),silent="graph", holdout = TRUE, accuracy="sMSE")

test_op <- data.frame(test$ID, SMA_test1$forecast)

colnames(test_op) <- c("ID","Count")
```

```{r}

dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "sma1.csv"), col_names = TRUE)


```



```{r}
x1 <- ts(train$Count, frequency=24*1)
x2 <- ts(train$Count, frequency=24*7)
x3 <- ts(train$Count, frequency=24*365)
```




```{r}

SES_auto1 <- HoltWinters(x1,beta=FALSE,gamma=FALSE)
SES_auto2 <- HoltWinters(x2,beta=FALSE,gamma=FALSE)
SES_auto3 <- HoltWinters(x3,beta=FALSE,gamma=FALSE)

```


```{r}
SES_auto1$SSE
SES_auto2$SSE
SES_auto3$SSE

```

```{r}


f1 <- forecast(SES_auto1,h=nrow(test))
#f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

write_csv(test_op, file.path(dir, "SES1.csv"), col_names = TRUE)


```



```{r}

DES_auto1 <- HoltWinters(x1,gamma=FALSE)
DES_auto2 <- HoltWinters(x2,gamma=FALSE)
DES_auto3 <- HoltWinters(x3,gamma=FALSE)

```


```{r}
DES_auto1$SSE
DES_auto2$SSE
DES_auto3$SSE

```

```{r}


f1 <- forecast(DES_auto1,h=nrow(test))
#f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

write_csv(test_op, file.path(dir, "DES1.csv"), col_names = TRUE)


```



```{r}

TES_auto1 <- HoltWinters(x1)
TES_auto2 <- HoltWinters(x2)
TES_auto3 <- HoltWinters(x3)

```


```{r}
TES_auto1$SSE
TES_auto2$SSE
TES_auto3$SSE

```

```{r}


f1 <- predict(TES_auto1,n.ahead =nrow(test))
f2 <- predict(TES_auto2,n.ahead =nrow(test))
f3 <- predict(TES_auto3,n.ahead =nrow(test))


```

```{r}
test_op1 <- data.frame(test$ID, exp(f1))
colnames(test_op1) <- c("ID","Count")

test_op2 <- data.frame(test$ID, exp(f2))
colnames(test_op2) <- c("ID","Count")

test_op3 <- data.frame(test$ID, exp(f3))
colnames(test_op3) <- c("ID","Count")



```


```{r}

write_csv(test_op1, file.path(dir, "TES1.csv"), col_names = TRUE)
write_csv(test_op2, file.path(dir, "TES2.csv"), col_names = TRUE)
write_csv(test_op3, file.path(dir, "TES3.csv"), col_names = TRUE)

```




```{r}

TES_auto4 <- HoltWinters(x1,seasonal = "multiplicative")
TES_auto5 <- HoltWinters(x2,seasonal = "multiplicative")
TES_auto6 <- HoltWinters(x3,seasonal = "multiplicative")

```


```{r}
TES_auto4$SSE
TES_auto5$SSE
TES_auto6$SSE

```

```{r}


f4 <- predict(TES_auto4,n.ahead =nrow(test))
f5 <- predict(TES_auto5,n.ahead =nrow(test))
f6 <- predict(TES_auto6,n.ahead =nrow(test))


```

```{r}
test_op4 <- data.frame(test$ID, f4)
colnames(test_op4) <- c("ID","Count")

test_op5 <- data.frame(test$ID, f5)
colnames(test_op5) <- c("ID","Count")

test_op6 <- data.frame(test$ID, f6)
colnames(test_op6) <- c("ID","Count")



```


```{r}

write_csv(test_op4, file.path(dir, "TES4.csv"), col_names = TRUE)
write_csv(test_op5, file.path(dir, "TES5.csv"), col_names = TRUE)
write_csv(test_op6, file.path(dir, "TES6.csv"), col_names = TRUE)

```




```{r}
CES_auto1 <- auto.ces(x1)
CES_auto2 <- auto.ces(x2)
CES_auto3 <- auto.ces(x3)

```


```{r}


f1 <- forecast(CES_auto1,h=nrow(test))
f2 <- forecast(CES_auto2,h=nrow(test))
f3 <- forecast(CES_auto3,h=nrow(test))

accuracy(f1)
accuracy(f2)
accuracy(f3)



```

```{r}
test_op1 <- data.frame(test$ID, f1$mean)
colnames(test_op1) <- c("ID","Count")

test_op2 <- data.frame(test$ID, f2$mean)
colnames(test_op2) <- c("ID","Count")

test_op3 <- data.frame(test$ID, f3$mean)
colnames(test_op3) <- c("ID","Count")



```


```{r}

write_csv(test_op1, file.path(dir, "CES1.csv"), col_names = TRUE)
write_csv(test_op2, file.path(dir, "CES2.csv"), col_names = TRUE)
write_csv(test_op3, file.path(dir, "CES3.csv"), col_names = TRUE)

```



#xgb

```{r}
#Creating features

train_x <- train
test_x <- test


train_x$Count <- log(train$Count) #log transformation

train_x$Datetime<-as.POSIXct(train$Datetime,"%d-%m-%Y %H:%M", tz="GMT")
test_x$Datetime<-as.POSIXct(test$Datetime,"%d-%m-%Y %H:%M", tz="GMT")

train_x$year<-as.numeric(format(train_x$Datetime, "%Y"))
test_x$year<-as.numeric(format(test_x$Datetime, "%Y"))


train_x$month<-as.numeric(format(train_x$Datetime, "%m"))
test_x$month<-as.numeric(format(test_x$Datetime, "%m"))


train_x$day<-as.numeric(format(train_x$Datetime, "%d"))
test_x$day<-as.numeric(format(test_x$Datetime, "%d"))


train_x$weekday<-as.factor(weekdays(train_x$Datetime))
test_x$weekday<-as.factor(weekdays(test_x$Datetime))

train_x$hour<-as.numeric(format(train_x$Datetime, "%H"))
test_x$hour<-as.numeric(format(test_x$Datetime, "%H"))
#train_x$hour<-as.factor(format(train_x$Datetime, "%H"))
#test_x$hour<-as.factor(format(test_x$Datetime, "%H"))



train_x$dow<-as.numeric(format(train_x$Datetime, "%w"))
test_x$dow<-as.numeric(format(test_x$Datetime, "%w"))




train_x$peak<-as.factor(ifelse(train_x$hour >= 2 & train_x$hour <=10,"np","p"))
test_x$peak<-as.factor(ifelse(test_x$hour >= 2 & test_x$hour <=10,"np","p"))



#train_x$weekend<-as.factor(ifelse(weekdays(train_x$Datetime)=="Saturday" | weekdays(train_x$Datetime)=="Sunday","Y","N"))
#test_x$weekend<-as.factor(ifelse(weekdays(test_x$Datetime)=="Saturday" | weekdays(test_x$Datetime)=="Sunday","Y","N"))



predictors<-c("year", "month", "day", "peak.p", "peak.np")


#predictors<-c("year", "month", "day", "weekday.Friday", "weekday.Monday", "weekday.Saturday", "weekday.Sunday", "weekday.Thursday", "weekday.Tuesday", "weekday.Wednesday", "peak.p", "peak.np")

#predictors<-c("Datetime", "year", "month", "day", "weekday.Friday", "weekday.Monday", "weekday.Saturday", "weekday.Sunday", "weekday.Thursday", "weekday.Tuesday", "weekday.Wednesday", "peak.p", "peak.np","weekend.Y", "weekend.N" )

#predictors<-c("Datetime", "year", "month", "day", "peak.p", "peak.np","weekend.Y", "weekend.N" )

dmy <- dummyVars(" ~ .", data = train_x, fullRank = F)
x_train <- data.frame(predict(dmy, newdata = train_x))


dmy <- dummyVars(" ~ .", data = test_x, fullRank = F)
x_test <- data.frame(predict(dmy, newdata = test_x))


#dtrain <- xgb.DMatrix(data=as.matrix(x_train[,predictors]), label=train_x$Count)
#dtest <- xgb.DMatrix(data=as.matrix(x_test[,predictors]))

#creating model

set.seed(101)
library(xgboost)
library(caret)

fitcontrol <- trainControl(method="cv",number=10,savePredictions='final')


model_xgb <- train(x_train[,predictors],
                  x_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)

#importance_matrix <- xgb.importance(predictors,model=model_xgb$finalModel)
#predictors2<-importance_matrix$Feature[1:5]

predict_model_xgb <- predict(model_xgb,x_test[,predictors])

test_op <- data.frame(test$ID, exp(predict_model_xgb))  #reverse log transformation
colnames(test_op) <- c("ID","Count")
write_csv(test_op, file.path(dir, "xgb7L.csv"), col_names = TRUE)


for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_xgbi <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_xgbi,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "xgbi.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}


k <- 0
for(i in 0:23)
{
  for(j in 0:6)
  {
    temp_train <- x_train %>% filter(hour==i & dow==j)
    temp_test <- x_test %>% filter(hour==i & dow==j)
    set.seed(101)
    model_xgbi <- train(temp_train[,predictors],
                    temp_train$Count,
                    method = 'xgbTree',
                    verbose = FALSE,
                    trControl = fitcontrol)
  
    test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_xgbi,temp_test[,predictors])))
    colnames(test_op) <- c("ID","Count")
    write_csv(test_op, file.path(dir, "xgbii.csv"), col_names=ifelse(k %in% 0, TRUE, FALSE), append=TRUE)
    k <- 1
    cat(i,j)
  }
  
}




for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  
  
  dtrain <- xgb.DMatrix(data=as.matrix(temp_train[,predictors]), label=temp_train$Count)
  dtest <- xgb.DMatrix(data=as.matrix(temp_test[,predictors]))
  
  param <- list(
  objective = "reg:linear",
  eval_metric = "rmse",  
  eta = runif(1, .01, .3),
  gamma = runif(1, 0.0, 0.2),
  subsample = runif(1, .6, .9),
  colsample_bytree = runif(1, .5, .8),
#  lambda = 2
  max_depth = sample(2:10, 1),
  min_child_weight = sample(1:40, 1),
  max_delta_step = sample(1:10, 1)
  )

  set.seed(101)
  
  cv_count <- xgb.cv(
  params = param, 
  data = dtrain, 
  nrounds = 500, 
  #  watchlist = watchlist,
  nfold = 10,  
  maximize = F,
  verbose = F
  #early_stopping_rounds = 20
  #print_every_n = 50
  )



  xgb_count <- xgb.train(
  params = param, 
  data = dtrain, 
  nrounds = 500, 
  #  watchlist = watchlist,
  maximize = T
  #  early_stopping_rounds = 20
  )
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(object=xgb_count, newdata=dtest)))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "xgbiM.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)

}




for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_rfi <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'rf',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_rfi,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "rfi.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}


for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_knni <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'knn',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_knni,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "knni.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}

for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_rparti <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'rpart',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_rparti,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "rparti.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}


for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_lmi <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'lm',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_lmi,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "lmi.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}


for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_svmli <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'svmLinear',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_svmli,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "svmli.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}



for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_svmri <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'svmRadial',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_svmri,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "svmri.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}


for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  set.seed(101)
  model_gbmi <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'gbm',
                  verbose = FALSE,
                  trControl = fitcontrol)
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_gbmi,temp_test[,predictors])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "gbmi.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}



r1 <- resamples(list(lm=model_lmi,rpart=model_rparti,rf=model_rfi,knn=model_knni,svml=model_svmli,svmr=model_svmri,gbm=model_gbmi,xgb=model_xgbi))
modelCor(r1)



for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  
  ######
  set.seed(101)
  model_lmi <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'lm',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  temp_train$OOF_pred_lmi<-model_lmi$pred$pred[order(model_lmi$pred$rowIndex)]

  set.seed(101)
  model_rparti <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'rpart',
                  #verbose = FALSE,
                  trControl = fitcontrol)
  
  temp_train$OOF_pred_rparti<-model_rparti$pred$pred[order(model_rparti$pred$rowIndex)]
  ######
  temp_test$OOF_pred_lmi <- predict(model_lmi,temp_test[,predictors])
  temp_test$OOF_pred_rparti <- predict(model_rparti,temp_test[,predictors])
  ######
  predictors_top <- c('OOF_pred_lmi','OOF_pred_rparti') 
  set.seed(101)
  model_xgbi_top <- train(temp_train[,predictors_top],
                  temp_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
  ######
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_xgbi_top,temp_test[,predictors_top])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "ensembi.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}




for(i in 0:23)
{
  temp_train <- x_train %>% filter(hour==i)
  temp_test <- x_test %>% filter(hour==i)
  
  ###ensemble 1 train
  set.seed(101)
  model_xgbi1 <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
  
  temp_train$OOF_pred_xgbi1<-model_xgbi1$pred$pred[order(model_xgbi1$pred$rowIndex)]

  ###ensemble 2 train
  set.seed(356)
  model_xgbi2 <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
  
  temp_train$OOF_pred_xgbi2<-model_xgbi2$pred$pred[order(model_xgbi2$pred$rowIndex)]

  ###ensemble 3 train
  set.seed(651)
  model_xgbi3 <- train(temp_train[,predictors],
                  temp_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)
  
  temp_train$OOF_pred_xgbi3<-model_xgbi3$pred$pred[order(model_xgbi3$pred$rowIndex)]
  
  ###ensemble 1/2/3 test

  temp_test$OOF_pred_xgbi1 <- predict(model_xgbi1,temp_test[,predictors])
  temp_test$OOF_pred_xgbi2 <- predict(model_xgbi2,temp_test[,predictors])
  temp_test$OOF_pred_xgbi3 <- predict(model_xgbi3,temp_test[,predictors])
  
  ###ensemble top train
  
  predictors_top <- c('OOF_pred_xgbi1','OOF_pred_xgbi2', 'OOF_pred_xgbi3') 
  
  set.seed(955)
  model_xgb_final <- train(temp_train[,predictors_top],
                  temp_train$Count,
                  method = 'xgbTree',
                  verbose = FALSE,
                  trControl = fitcontrol)

  ###ensemble top test
  
  test_op <- data.frame(ID=temp_test$ID,Count=exp(predict(model_xgb_final,temp_test[,predictors_top])))
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "xgb_ensemble.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}






```



```{r}



```




```{r}

#prediction
predict_model_xgb1 <- predict(model_xgb1,x_test[,predictors])


```

```{r}
test_op <- data.frame(test$ID, predict_model_xgb1)

colnames(test_op) <- c("ID","Count")
```


```{r}

write_csv(test_op, file.path(dir, "xgb2.csv"), col_names = TRUE)


```



```{r}


param <- list(
  objective = "reg:linear",
  eval_metric = "rmse",  
  eta = 0.01,
#  lambda = 2
  max_depth = 2
)



set.seed(101)

xgb_nsales <- xgb.train(
  params = param, 
  data = dtrain, 
  nrounds = 5000, 
  #  watchlist = watchlist,
  maximize = T
  #  early_stopping_rounds = 20
)

```


```{r}

#prediction
predict_model_xgb2 <- predict(xgb_nsales,newdata=dtest)


```

```{r}
test_op <- data.frame(test$ID, predict_model_xgb2)

colnames(test_op) <- c("ID","Count")
```


```{r}

write_csv(test_op, file.path(dir, "xgb2.csv"), col_names = TRUE)


```


#arimax



```{r}

#y=(diff(x,1))
arimax_model <- auto.arima(x1, xreg=fourier(x,K=2))

#pred <- predict (model, newxreg=nasdaq.predict)


```




```{r}


f1 <- forecast(arimax_model,xreg=fourier(x,K=2,h=nrow(test)))
#f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, f1$mean)

colnames(test_op) <- c("ID","Count")
```


```{r}

#dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "arima2.csv"), col_names = TRUE)


```

```{r}

x4<- ts(log(train$Count), frequency=24*1)
x5<- ts(log(train$Count), frequency=24*7)
x6<- ts(log(train$Count), frequency=24*365)


#model_ets0 <- ets(x)
model_ets1 <- es(ts(c(train$Count,rep(500,nrow(test))),frequency=24),h=nrow(test),holdout = TRUE,xreg = xreg_tot,updateX=TRUE)
#model_ets2 <- ets(x2)
#model_ets3 <- ets(x3)


```


```{r}


f1 <- forecast(model_ets1,h=nrow(test))
#f1 <- predict(tslm_add2,n.ahead=nrow(test))

```

```{r}
test_op <- data.frame(test$ID, model_ets1$forecast)

colnames(test_op) <- c("ID","Count")
```


```{r}

#dir <- "C:\\Users\\Srimala Bharadwaj\\Desktop\\Data science\\AV\\JetRail"
write_csv(test_op, file.path(dir, "ets1.csv"), col_names = TRUE)


```

#ces with xreg

```{r}

train_x <- train
test_x <- test


#train_x$Count <- log(train$Count) #log transformation

train_x$Datetime<-as.POSIXct(train$Datetime,"%d-%m-%Y %H:%M", tz="GMT")
test_x$Datetime<-as.POSIXct(test$Datetime,"%d-%m-%Y %H:%M", tz="GMT")

#Creating features

train_x$year<-as.numeric(format(train_x$Datetime, "%Y"))
test_x$year<-as.numeric(format(test_x$Datetime, "%Y"))


train_x$month<-as.numeric(format(train_x$Datetime, "%m"))
test_x$month<-as.numeric(format(test_x$Datetime, "%m"))


train_x$day<-as.numeric(format(train_x$Datetime, "%d"))
test_x$day<-as.numeric(format(test_x$Datetime, "%d"))


train_x$weekday<-as.factor(weekdays(train_x$Datetime))
test_x$weekday<-as.factor(weekdays(test_x$Datetime))

train_x$hour<-as.numeric(format(train_x$Datetime, "%H"))
test_x$hour<-as.numeric(format(test_x$Datetime, "%H"))


train_x$peak<-as.factor(ifelse(train_x$hour >= 2 & train_x$hour <=10,"np","p"))
test_x$peak<-as.factor(ifelse(test_x$hour >= 2 & test_x$hour <=10,"np","p"))

train_x$weekend<-as.factor(ifelse(weekdays(train_x$Datetime)=="Saturday" | weekdays(train_x$Datetime)=="Sunday","Y","N"))
test_x$weekend<-as.factor(ifelse(weekdays(test_x$Datetime)=="Saturday" | weekdays(test_x$Datetime)=="Sunday","Y","N"))


#predictors<-c("year", "month", "day", "weekday.Friday", "weekday.Monday", "weekday.Saturday", "weekday.Sunday", "weekday.Thursday", "weekday.Tuesday", "weekday.Wednesday", "peak.p", "peak.np","weekend.Y", "weekend.N" )

predictors<-c("day","peak.p", "peak.np")

dmy <- dummyVars(" ~ .", data = train_x, fullRank = F)
x_train <- data.frame(predict(dmy, newdata = train_x))


dmy <- dummyVars(" ~ .", data = test_x, fullRank = F)
x_test <- data.frame(predict(dmy, newdata = test_x))


xreg_train <- as.matrix(x_train[,predictors])
xreg_test <- as.matrix(x_test[,predictors])


xreg_tot <- rbind(xreg_train,xreg_test)

x1_all <- ts(c(train$Count,rep(0,nrow(test))), frequency=24*1)

```


```{r}
CES_auto1x <- auto.ces(x1_all,xreg=xreg_tot,holdout=TRUE,h=nrow(test),updateX=TRUE)
#CES_auto2x <- auto.ces(x2,xreg=xreg_train,xregDo = "select")
#CES_auto3x <- auto.ces(x3,xreg=xreg_train,xregDo = "select")

```


```{r}


f1 <- forecast(CES_auto1x,xreg=xreg_test,h=nrow(test),holdout=TRUE)
#f2 <- forecast(CES_auto2x,h=nrow(test))
#f3 <- forecast(CES_auto3x,h=nrow(test))

accuracy(f1)
#accuracy(f2)
#accuracy(f3)



```

```{r}
test_op1 <- data.frame(test$ID, f1$mean)
colnames(test_op1) <- c("ID","Count")

test_op2 <- data.frame(test$ID, f2$mean)
colnames(test_op2) <- c("ID","Count")

test_op3 <- data.frame(test$ID, f3$mean)
colnames(test_op3) <- c("ID","Count")

```






```{r}

write_csv(test_op1, file.path(dir, "CES1x.csv"), col_names = TRUE)
write_csv(test_op2, file.path(dir, "CES2x.csv"), col_names = TRUE)
write_csv(test_op3, file.path(dir, "CES3x.csv"), col_names = TRUE)

```


```{r}

#SMA

train_x <- train
test_x <- test


train_x$Datetime<-as.POSIXct(train$Datetime,"%d-%m-%Y %H:%M", tz="GMT")
test_x$Datetime<-as.POSIXct(test$Datetime,"%d-%m-%Y %H:%M", tz="GMT")

#Creating features

train_x$hour<-as.numeric(format(train_x$Datetime, "%H"))
test_x$hour<-as.numeric(format(test_x$Datetime, "%H"))

for(i in 0:23)
{
  temp_train <- train_x %>% filter(hour==i)
  temp_test <- test_x %>% filter(hour==i)
  SMA_i <- sma(ts(temp_train$Count, frequency =365, start=c(2012,8,25)), h=nrow(temp_test), silent="graph",ic="AIC",cfType="RMSE")
  test_op <- data.frame(ID=temp_test$ID,Count=SMA_i$forecast)
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "smar.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
  
}


```



```{r}

#CES id

train_x <- train
test_x <- test


train_x$Datetime<-as.POSIXct(train$Datetime,"%d-%m-%Y %H:%M", tz="GMT")
test_x$Datetime<-as.POSIXct(test$Datetime,"%d-%m-%Y %H:%M", tz="GMT")

#Creating features

train_x$dow<-as.numeric(format(train_x$Datetime, "%w"))
test_x$dow<-as.numeric(format(test_x$Datetime, "%w"))

for(i in 0:6)
{
  temp_train <- train_x %>% filter(dow==i)
  temp_test <- test_x %>% filter(dow==i)
  
  ETS_autoi <- es(ts(temp_train$Count, frequency =52, start=c(2012,34)))
  test_op <- data.frame(ID=temp_test$ID,Count=forecast(ETS_autoi,h=nrow(temp_test))$mean)
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "etsid.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
  
}


```


```{r}

#ETS 

train_x <- train
test_x <- test


train_x$Datetime<-as.POSIXct(train$Datetime,"%d-%m-%Y %H:%M", tz="GMT")
test_x$Datetime<-as.POSIXct(test$Datetime,"%d-%m-%Y %H:%M", tz="GMT")

#Creating features

train_x$hour<-as.numeric(format(train_x$Datetime, "%H"))
test_x$hour<-as.numeric(format(test_x$Datetime, "%H"))

for(i in 0:23)
{
  temp_train <- train_x %>% filter(hour==i)
  temp_test <- test_x %>% filter(hour==i)
  ETS_autoi <- es(ts(temp_train$Count, frequency =365, start=c(2012,8,25)))
  test_op <- data.frame(ID=temp_test$ID,Count=forecast(ETS_autoi,h=nrow(temp_test))$mean)
  colnames(test_op) <- c("ID","Count")
  write_csv(test_op, file.path(dir, "etsi.csv"), col_names=ifelse(i %in% 0, TRUE, FALSE), append=TRUE)
  print(i)
  
}


```