### Recommendation engine 2nd part

---
title: "Movie recommendation engine 2"
output: 
  html_document: 
    smart: no
---

http://xgboost.readthedocs.io/en/latest/model.html
https://www.analyticsvidhya.com/blog/2016/01/xgboost-algorithm-easy-steps/


```{r}
library('dplyr')
library('stringr')
library('stringi')
```


```{r}

#Loading the data
movies_recomm <- read.csv('movie_metadata.csv',stringsAsFactors=FALSE)


#Removing duplicate movies
idx_dup <- which(duplicated(movies_recomm$movie_title)==TRUE)
movies_recomm <- movies_recomm[-idx_dup,]

#considering movies with atleast 1000 votes for recommendation
movies_recomm <- movies_recomm %>% filter(num_voted_users>=1000)

```

#get unique genres

```{r}
genre_list <- NULL
genr <- function(a) 
{
  k <- unlist(strsplit(a, "|",fixed = TRUE))
  genre_list <- unique(union(k,genre_list))
}

genre_list <- genr(movies_recomm$genres)


genre_list <- genre_list[-c(15,20)]

genre_list <- sort(genre_list)

genre_list
```


###seggregate movies by genres


```{r}
genre_matrix2 <- matrix(0, dim(movies_recomm)[1], length(genre_list))
colnames(genre_matrix2) <- genre_list

row1 <<- 1

upd_genr <- function(a) 
{
  k <- unlist(strsplit(a, "|",fixed = TRUE))
  
  for (i in 1:length(k)) 
  {
    col1 <- which(k[i]==colnames(genre_matrix2))
    
    genre_matrix2[row1,col1] <<- 1
    
  }
  row1 <<- row1 + 1
  
}

temp <- sapply(movies_recomm$genres,upd_genr)

head(genre_matrix2)

```

### Structure the data


```{r}

movies_genre <- as.data.frame(genre_matrix2)

movies_genre <- movies_genre %>% mutate(movie_title=movies_recomm$movie_title,language=movies_recomm$language,imdb_score=movies_recomm$imdb_score)

glimpse(movies_genre)
```


### Function to get Top10 movies

```{r}

top10 <- function(my.genre)
{
  idx <<- which(colnames(movies_genre)==my.genre)
  temp <<- movies_genre[movies_genre[,idx]>0,] %>% select(idx,24:26) %>%  arrange(desc(imdb_score)) %>% top_n(10)
}

```


### Get Top10 movies in user selected Genre


```{r}
#List of genres to choose from
p1 <- paste(1:length(genre_list),'-',genre_list)
cat(p1,sep='\n')

#Take user input genre
my.genre.number <- readline(prompt="Enter the genre (number) you would like to choose:")
#my.genre.number <- as.integer(my.genre.number)
my.genre <- genre_list[as.integer(my.genre.number)]

#Call the function for Top10 movies
top10(my.genre)

#Top 10 movies in user selected genre
t1 <- str_trim(temp$movie_title,"right")
result <- paste0(t1,"(",temp$imdb_score,")")
cat('\nThe Recommended Top 10',my.genre,'movies are:\n\n')
cat(result,sep='\n')

```





